LinhcosMVC/LinhcosMVC/Controllers/ClientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LinhcosMVC.Controllers
{
    public class ClientController : Controller
    {
        //
        // GET: /Client/

        //public ActionResult Home()
        //{
        //    return View();
        //}
        public ActionResult Home1()
        {
            return View();
        }

        public ActionResult Contact()
        {
            //var gt = from t in data.TheLoaiTinTucs select t;
            //return View(gt);
            return View();
        }
    }
}

LinhcosMVC/LinhcosMVC/Controllers/SanPhamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LinhcosMVC.Models;

namespace LinhcosMVC.Controllers
{
    public class SanPhamController : Controller
    {

        LinhcosSQLDataContext data = new LinhcosSQLDataContext();

        private List<SanPham> spham(int count)
        {
            return data.SanPhams.Take(count).ToList();
        }

        public ActionResult Index()
        {
            var SanPhamMoi = spham(16);
            return View(SanPhamMoi);
        }

        public ActionResult SPTheoLoai(string maloai)
        {
            var sptheoDM = data.SanPhams.Where(a => a.MaLoaiSP == maloai).Select(a=>a);
            return View(sptheoDM);
        }

        public ActionResult Details(int masp)
        {
            var chitiet = data.SanPhams.Where(m => m.MaSP == masp).First();
            return View(chitiet);
        }
    }
}

LinhcosMVC/LinhcosMVC/Controllers/TinTucController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LinhcosMVC.Models;

namespace LinhcosMVC.Controllers
{
    public class TinTucController : Controller
    {
        //
        // GET: /TinTuc/

        // Tạo đối tượng chứa cơ sở dữ liệu tin tức
        LinhcosSQLDataContext data = new LinhcosSQLDataContext();

        // lấy tin mới nhất
        private List<TinTuc> Laytinmoi(int count)
        {
            return data.TinTucs.OrderByDescending(a => a.NgayDang).Take(count).ToList();
        }


        private List<TinTuc> AllTinTuc (int count)
        {
            return data.TinTucs.Take(count).ToList();
        }

        public ActionResult IndexTinTuc()
        {
            //ViewBag.NoiDung = "Chào mừng đến với trang tin tức";

            var alltin = AllTinTuc(3);
            return View(alltin);
            //var alltintuc = from tt in data.TinTucs select tt;
            //return View(alltintuc);

        }

        public ActionResult TinTucMoiNhat()
        {
            //// lấy 3 tin mới nhất
            ////var tinmoi = Laytinmoi(5);
            //return View(tinmoi);
            var tinmoi = Laytinmoi(3);
            return PartialView(tinmoi);
        }

        public ActionResult ChiTietTT(int matin)
        {
            var chitiet = data.TinTucs.Where(m => m.MaTin == matin).First();
            return View(chitiet);
        }
    }
}

LinhcosMVC/LinhcosMVC/Views/Client/Contact.cshtml
@{
    ViewBag.Title = "Contact";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<h2>Contact</h2>
<section class="hero">
    <div class="container">
        <!-- Breadcrumbs -->
        <ol class="breadcrumb justify-content-center">
            <li class="breadcrumb-item"><a href="index.html">Home</a></li>
            <li class="breadcrumb-item active">Contact        </li>
        </ol>
        <!-- Hero Content-->
        <div class="hero-content pb-5 text-center">
            <h1 class="hero-heading">Contact</h1>
            <div class="row">
                <div class="col-xl-8 offset-xl-2">
                    <p class="lead text-muted">
                        Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis.
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>

<section style="background: #fafafa;" class="py-6">
    <div class="container">
        <div class="row">
            <div class="col-md-4 text-center text-md-left">
                <svg class="svg-icon svg-icon-light text-primary w-3rem h-3rem mb-3">
                    <use xlink:href="#navigation-map-1"> </use>
                </svg>
                <h4 class="ff-base">Address</h4>
                <p class="text-muted">13/25 New Avenue<br>New Heaven, 45Y 73J<br>England, <strong>Great Britain</strong></p>
            </div>
            <div class="col-md-4 text-center text-md-left">
                <svg class="svg-icon svg-icon-light text-primary w-3rem h-3rem mb-3">
                    <use xlink:href="#audio-call-1"> </use>
                </svg>
                <h4 class="ff-base">Call center</h4>
                <p class="text-muted">Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
                <p class="text-muted"><strong>+33 555 444 333</strong></p>
            </div>
            <div class="col-md-4 text-center text-md-left">
                <svg class="svg-icon svg-icon-light text-primary w-3rem h-3rem mb-3">
                    <use xlink:href="#mail-1"> </use>
                </svg>
                <h4 class="ff-base">Electronic support</h4>
                <p class="text-muted">Please feel free to write an email to us or to use our electronic ticketing system.</p>
                <ul class="list-unstyled text-muted">
                    <li>info@sell.com</li>
                    <li>support@sell.com</li>
                </ul>
            </div>
        </div>
    </div>
</section>

LinhcosMVC/LinhcosMVC/Views/Client/Home.cshtml
@{
    ViewBag.Title = "Home";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
    <div class="container col-lg-12">
        <div id="myCarousel" class="carousel carousel-fade slide border " data-ride="carousel">
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img class="d-block w-100" src="~/Asset/Pic/slideshow_1.png" alt="1" />
                </div>
                <div class="carousel-item">
                    <img class="d-block w-100" src="~/Asset/Pic/slideshow_2.jpg" alt="2" />
                </div>
                <div class="carousel-item">
                    <img class="d-block w-100" src="~/Asset/Pic/slideshow_3.png" alt="3" />
                </div>
            </div>
            <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>

            <div id="Div1" class="carousel slide border" data-ride="carousel">
                <!-- Indicators -->
                <ol class="carousel-indicators">
                    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                    <li data-target="#myCarousel" data-slide-to="1"></li>
                    <li data-target="#myCarousel" data-slide-to="2"></li>
                </ol>
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
</div>

@*EndSlideShow*@

LinhcosMVC/LinhcosMVC/Views/Client/Home1.cshtml
@{
    ViewBag.Title = "Home1";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- Hero Section-->
<section class="home-full-slider-wrapper mb-10px">
    <!-- Hero Slider-->
    <div class="container-fluid">
        <div id="myCarousel" class="carousel slide border" data-ride="carousel">
            <div class="carousel-inner">
                <div class="carousel-item active ">
                    <img class="d-block w-100" src="~/Asset/Pic/Slideshow/slideshow_1.png" alt="1" style="height: 639.2px;">
                    <div class="carousel-caption d-none d-sm-block">
                        <small>

                            <h5 class="text-uppercase text-white font-weight-light mb-4 letter-spacing-5">Just arrived</h5>
                            <h1 class="mb-4 display-2 text-uppercase font-weight-bold">NEW PRODUCT</h1>
                            <p class="lead mb-5">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
                            <p><a href="#" class="btn btn-light">Start shopping</a></p>

                        </small>
                    </div>
                </div>
                <div class="carousel-item">
                    <img class="d-block w-100" src="~/Asset/Pic/Slideshow/slideshow_2.jpg" alt="2" style="height: 639.2px;">
                    <div class="carousel-caption d-none d-sm-block">
                        <small>
                            <p><a href="@Url.Action("Index","SanPham")" class="btn btn-light">View collection</a></p>
                        </small>
                    </div>
                </div>
                <div class="carousel-item">
                    <img class="d-block w-100" src="~/Asset/Pic/Slideshow/slideshow_3.png" alt="3" style="height: 639.2px;">
                    <div class="carousel-caption d-none d-sm-block">
                        <small>

                            <h5 class="text-uppercase text-white font-weight-light mb-4 letter-spacing-5">Just arrived</h5>
                            <h1 class="mb-5 display-2 font-weight-bold text-serif">SKIN CARE</h1>
                            <p class="lead mb-4">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
                            <p><a href="@Url.Action("Index","SanPham")" class="btn btn-light">View collection</a></p>
                        </small>
                    </div>
                </div>
            </div>
            <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
</section>

<section>
    <div class="container-fluid px-5px">
        <div class="row mx-0">
            <div class="col-md-6 mb-10px px-5px">
                <div class="card border-0 text-white text-center">
                    <img src="~/Asset/Pic/cardmenu/1.jpeg" alt="Card image" class="card-img">
                    <div class="card-img-overlay d-flex align-items-center">
                        <div class="w-100 py-3">
                            <h2 class="display-3 font-weight-bold mb-4">New</h2>
                            <a href="@Url.Action("Index","SanPham")" class="btn btn-light">Shop now</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6 mb-10px px-5px">
                <div class="card border-0 text-white text-center">
                    <img src="~/Asset/Pic/cardmenu/2.jpeg" alt="Card image" class="card-img">
                    <div class="card-img-overlay d-flex align-items-center">
                        <div class="w-100 py-3">
                            <h2 class="display-3 font-weight-bold mb-4">Make up</h2>
                            <a href="@Url.Action("Index","SanPham")" class="btn btn-light">Shop now</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row mx-0">
            <div class="col-lg-4 mb-10px px-5px">
                <div class="card border-0 text-center text-white">
                    <img src="~/Asset/Pic/cardmenu/3.jpeg" alt="Card image" class="card-img">
                    <div class="card-img-overlay d-flex align-items-center">
                        <div class="w-100">
                            <h2 class="display-4 mb-4">Skin care</h2>
                            <a href="@Url.Action("Index","SanPham")" class="btn btn-link text-white">Shop now <i class="fa-arrow-right fa ml-2"></i></a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 mb-10px px-5px">
                <div class="card border-0 text-center text-white">
                    <img src="~/Asset/Pic/cardmenu/4.jpeg" alt="Card image" class="card-img">
                    <div class="card-img-overlay d-flex align-items-center">
                        <div class="w-100">
                            <h2 class="display-4 mb-4">Review & News</h2>
                            <a href="@Url.Action("IndexTinTuc","TinTuc")" class="btn btn-link text-white">See more <i class="fa-arrow-right fa ml-2"></i></a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 mb-10px px-5px">
                <div class="card border-0 text-center text-white">
                    <img src="~/Asset/Pic/cardmenu/5.jpeg " alt="Card image" class="card-img">
                    <div class="card-img-overlay d-flex align-items-center">
                        <div class="w-100">
                            <h2 class="display-4 mb-4">Contact</h2>
                            <a href="@Url.Action("Contact","Client")" class="btn btn-link text-white">See more <i class="fa-arrow-right fa ml-2"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>